FROM node:24-alpine AS builder
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build
FROM node:24-alpine AS runner
COPY package*.json ./
RUN npm ci --only=production 
COPY --from=builder ./dist /app/dist
EXPOSE 8080
CMD [ "npm", "run", "start:prod" ]