name: quizly-production-api
services:
  quizly-api-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '${PORT}:8080'
    env_file:
      - ./.env.production.local
    volumes:
      - ./src:/app/src
  postgres-prod:
    image: postgres:18
    container_name: postgres_prod_container
    env_file:
      - ./.env.production.local
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./pgdata/prod:/var/lib/postgresql/data/pgdata
volumes:
  pgdata:
    driver: local
