FROM node:24-alpine AS builder
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build

FROM node:24-alpine AS runner
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev 
COPY --from=builder /app/dist ./dist
EXPOSE 8080
CMD [ "npm", "run", "start:prod" ]